backend:
  name: git-gateway
  branch: master

media_folder: "content/posts/images/"
public_folder: "./images/"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., yy-mm-dd-slug.md; {{year}}-{{month}}-{{day}}-{{slug}}
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "cover_image", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "menuPage"
    label: "Menu Pages"
    folder: "content/pages/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "data"
    label: "Data"
    files:
      - name: "quote"
        label: "Quote (Below 'Tabie Wolstencroft')"
        file: "src/data/quote.yml"
        fields:
          - { label: "Quote", name: "quote", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          