backend:
  name: git-gateway
  branch: master

media_folder: "content/posts/images/"
public_folder: "/images/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., yy-mm-dd-slug.md; {{year}}-{{month}}-{{day}}-{{slug}}
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "data"
    label: "Data"
    files:
      - name: "quote"
        label: "Quote (Below 'Tabie Wolstencroft')"
        file: "src/data/quote.yml"
        fields:
          - { label: "Quote", name: "quote", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
      # TODO: readd about, and about page
      # - name: "about"
      #   label: "About"
      #   file: "src/data/About.yml"
      #   fields:
      #     - { label: "Title", name: "title", widget: "string", default: "About" }
      #     - name: "items"
      #       label: "Items"
      #       widget: "list"
      #       fields:
      #         - { label: "Title", name: "title", widget: "string" }
      #         - { label: "Description", name: "description", widget: "text" }

      # TODO: readd contact, and contact page
      # - name: "contact"
      #   label: "Contact"
      #   file: "src/data/Contact.yml"
      #   fields:
      #     - { label: "Title", name: "title", widget: "string", default: "Contact" }
      #     - { label: "Description", name: "description", widget: "text" }
